[package]
name = "ex_extractous"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_extractous"
crate-type = ["cdylib"]

[dependencies]
extractous = "=0.3.0"
rustler = { version = "0.36.1", features = ["nif_version_2_17"] }
